### ISSUE TITLE
GetFormatterParts throws exception in Firefox/Chromium 96 browsers...

### ISSUE THREAD

**Issue by tvanriper** [js-temporal/temporal-polyfill#120]
In js-temporal.js, around line 8470, this library uses an interesting series of comma assignments that I think break in the latest versions of certain browsers out there.

I used the following code to fix it:

```
    var _datetime$split = datetime.split(/,\s+/);
    var _datetime$split2 = _slicedToArray(_datetime$split, 3);
    var date = _datetime$split2[0],
        fullYear = _datetime$split2[1],
        time = _datetime$split2[2];

    var _date$split = date.split(' ');
    var _date$split2 = _slicedToArray(_date$split, 2);
    var month = _date$split2[0],

        day = _date$split2[1];

    var _fullYear$split = fullYear.split(' ');
    var _fullYear$split2 = _slicedToArray(_fullYear$split, 2);
    var year = _fullYear$split2[0],
        era = _fullYear$split2[1];

    var _time$split = time.split(':');
    var _time$split2 = _slicedToArray(_time$split, 3);
    var hour = _time$split2[0],
        minute = _time$split2[1],
        second = _time$split2[2];
```

I've provided the full file here:

[js-temporal.js.zip](https://github.com/js-temporal/temporal-polyfill/files/7881925/js-temporal.js.zip)

Er, I can see about providing a proper submission.

**Comment by tvanriper** [comment]
Never mind, this is a dupe of another issue that you've already fixed.  I'm working off a bad dependency. My apologies.

**Comment by ptomato** [comment]
Thanks for taking the time to report it nonetheless!
