### ISSUE TITLE
DateTimeFormatOptions typing override missing calendar

### ISSUE THREAD

**Issue by RandomEngy** [js-temporal/temporal-polyfill#124]
The TC39 docs [have this example](https://tc39.es/proposal-temporal/docs/plainmonthday.html#toLocaleString):

```js
monthDay.toLocaleString(locales, { calendar: monthDay.calendar });
```

But it doesn't compile for me with the polyfill library unless I do this:

```js
monthDay.toLocaleString(locales, { calendar: monthDay.calendar.id });
```

The `options` parameter takes `calendar: string | undefined` while `monthDay.calendar` is a `Temporal.CalendarProtocol`. I thought the example code might have been incorrect, but it turns out that [if you pass in a `Temporal.Calendar` there it is interpreted correctly](https://github.com/tc39/proposal-temporal/pull/2023).

The polyfill library doctors the Intl.DateTimeFormatOptions. It looks like it redeclares timeZone, but I think also should be redeclaring the calendar property to also accept `Temporal.CalendarProtocol`.

```typescript
  export interface DateTimeFormatOptions extends Omit<globalThis.Intl.DateTimeFormatOptions, 'timeZone'> {
    timeZone?: string | Temporal.TimeZoneProtocol;
    // TODO: remove the props below after TS lib declarations are updated
    dayPeriod?: 'narrow' | 'short' | 'long';
    dateStyle?: 'full' | 'long' | 'medium' | 'short';
    timeStyle?: 'full' | 'long' | 'medium' | 'short';
  }
```

**Comment by justingrant** [comment]
Good catch. Fix coming soon.
