### ISSUE TITLE
Expose *Like utility types 

### ISSUE THREAD

**Issue by bobthemighty** [js-temporal/temporal-polyfill#146]
For a TDD kata I was writing, I wanted to be able to say:

`const isMorning = (t: PlainTimeLike) => t.hour < 12 ` but the PlainTimeLike type isn't exposed. Given that it makes up part of the interface of methods like `PlainDate.toPlainDateTime()` is there a chance you will expose these types?

**Comment by 12wrigja** [comment]
https://github.com/js-temporal/temporal-polyfill/blob/2f6e6b43267113a213d08b70be8ea72e8075aa1a/index.d.ts#L999

The PlainTimeLike type is defined as part of the Temporal namespace in the package's typings, so maybe try writing `Temporal.PlainTimeLike` instead?

**Comment by bobthemighty** [comment]
Apologies! I'm using a different polyfill, with a confusingly similar name.

**Comment by 12wrigja** [comment]
No worries! Which one, if you don't mind me asking? If it's not listed in the [polyfill table](https://github.com/tc39/proposal-temporal#polyfills) maybe ask the maintainers to add it?

**Comment by bobthemighty** [comment]
The full-calendar one.
