### ISSUE TITLE
Time Ambiguity issue?

### ISSUE THREAD

**Issue by KarlLivesey** [js-temporal/temporal-polyfill#154]
So from my understanding the way Temporal will handle ambiguous times due to DST is if for example

`{ timeZone: 'Europe/London', year: 2022, month: 3, day: 27, hour: 1, minute: 30 };`

Was used this would under the current give either:

2022-03-27T02:30:00+01:00[Europe/London] OR 2022-03-27T00:30:00+00:00[Europe/London] dependent on disambiguation however. My requirement is to return is 2022-03-27T00:59:99.999+00:00 (the last possible time before 01:30) as the requirement is that a job is done BEFORE 01:30 clock time and naturally 02:30 is naturally after 01:30 and 00:30 is 30 minutes before the jump, therefore, moving the latest time forward by 30 minutes. is this possible under the current framework?

**Comment by justingrant** [comment]
There's no one-call way to do this in Temporal, but it should be fairly straightforward to do it as follows:

```js
function customZonedDateTimeCustomDisambiguationBefore(props) {
  const earlier = Temporal.ZonedDateTime.from(props, { disambiguation: 'earlier'});
  const later = Temporal.ZonedDateTime.from(props, { disambiguation: 'later'});
  if (earlier.equals(later)) return earlier;
  const { timeZone } = later;
  const transition = timeZone.getPreviousTransition(later.toInstant());
  const beforeTransition = transition.subtract({ nanoseconds: 1 });
  return beforeTransition.toZonedDateTimeISO(timeZone);
}

customZonedDateTimeCustomDisambiguationBefore(
  { timeZone: 'Europe/London', year: 2022, month: 3, day: 27, hour: 1, minute: 30 }
);
// => 2022-03-27T00:59:59.999999999+00:00[Europe/London]
```

**Comment by KarlLivesey** [comment]
@justingrant thats great! I've made a slight change so it can deal with repeats in the hoped-for way see below.

```
function customZonedDateTimeCustomDisambiguationBefore(timezone,plaindate) {

  tz = new Temporal.TimeZone(timezone);
  const instants = tz.getPossibleInstantsFor(plaindate);
  
  switch(instants.length){
    case 0:
      const transition = tz.getPreviousTransition(tz.getInstantFor(plaindate, { disambiguation: 'later'}));
      const beforeTransition = transition.subtract({ nanoseconds: 1 });
      return beforeTransition;
    default:
    	return instants[0];
  }
}

tz = new Temporal.TimeZone('Europe/London');

skipSimple = {year: 2022, month: 3, day: 27, hour: 1, minute: 30 };
doubleSimple = {year: 2022, month: 10, day: 30, hour: 1, minute: 30 };
normalSimple = {year: 2022, month: 10, day: 30, hour: 10, minute: 30 };

const skip = customZonedDateTimeCustomDisambiguationBefore('Europe/London', skipSimple);
const double = customZonedDateTimeCustomDisambiguationBefore('Europe/London', doubleSimple);
const normal = customZonedDateTimeCustomDisambiguationBefore('Europe/London', normalSimple);

console.log(skip.toString());
console.log(double.toString());
console.log(normal.toString());
```

**Comment by ptomato** [comment]
Custom disambiguation behaviour is indeed the main reason why the proposal has `getPossibleInstantsFor` :smile: 

The proposal website actually has a cookbook example on this topic, I haven't looked too closely in how far you landed on the same result, but it may still be helpful? https://tc39.es/proposal-temporal/docs/cookbook.html#preserving-local-time

**Comment by KarlLivesey** [comment]
Hmm YEah I hit pretty close with a slight twist and it allows cliplater good idea though
