### ISSUE TITLE
Get time zone abbreviation?

### ISSUE THREAD

**Issue by KarlLivesey** [js-temporal/temporal-polyfill#160]
Maybe I'm being blind but I don't see anywhere to get the timezone abbreviation? what I want is something like the below

```
console.log(Temporal.Instant.from('2020-01-14T00:31:00.065858086Z').toZonedDateTimeISO('Europe/London').abbreviation); ==> 'GMT'
console.log(Temporal.Instant.from('2020-06-14T00:31:00.065858086Z').toZonedDateTimeISO('Europe/London').abbreviation); ==> 'BST'
```

**Comment by 12wrigja** [comment]
Looking over the docs (https://tc39.es/proposal-temporal/docs/timezone.html) it seems that we canonicalize any identifier and return that as the ID, so presumably the abbreviated version is known to us but isn't exposed in the API surface currently.

You might find this a better question to ask in the API Specification repository: https://github.com/tc39/proposal-temporal - we only implement that API surface, so any additions would need to be discussed over there first.

Looking over the way we've implemented this, it seems we rely on the Intl dataset to do canonicalization for us: https://github.com/js-temporal/temporal-polyfill/blob/a01ca8a438e6b43f810a65bd50ee8b46458699e4/lib/ecmascript.ts#L2740

**Comment by KarlLivesey** [comment]
right but the key answer to this at the moment is it's not a bug it's expected behaviour

**Comment by justingrant** [comment]
I answered this over in https://github.com/tc39/proposal-temporal/issues/2257#issuecomment-1151890445. Let's continue the discussion over there.  I'll close this issue.
