### ISSUE TITLE
Infinite loop using duration.total

### ISSUE THREAD

**Issue by paulirish** [js-temporal/temporal-polyfill#180]
I came across an infinite loop…   I'm using the latest npm package. (and using parcel to use it in the browser)

minimal repro:

```js
const nowZoned = Temporal.Now.zonedDateTime(new Intl.DateTimeFormat().resolvedOptions().calendar);
Temporal.Duration.from('-PT22H').total({unit: 'years', relativeTo: nowZoned});
```

It seems to be hung in the `PrepareTemporalFields()` loop.

**Comment by 12wrigja** [comment]
I think it's actually getting stuck here: https://github.com/js-temporal/temporal-polyfill/blob/02ae80dd2fcd978abd4ca5949d529c0eb7f706a6/lib/calendar.ts#L1144-L1152

As far as I can tell all calls to PrepareTemporalFields do terminate correctly.

**Comment by 12wrigja** [comment]
This also happens using the latest spec-polyfill.

The actual call that seems to be problematic is

```
RoundDuration(0,0,0,0,-22,0,0,0,0,0,1,'year','trunc', Temporal.Now.zonedDateTime(new Intl.DateTimeFormat().resolvedOptions().calendar))
```

which eventually tries to determine the number of years passed between two identical dates (https://github.com/js-temporal/temporal-polyfill/blob/02ae80dd2fcd978abd4ca5949d529c0eb7f706a6/lib/ecmascript.ts#L5705, `yearsLater.equals(yearsMonthsLater) === true`) and this causes an infinite loop within CalendarDateUntil.

@ptomato thoughts?

**Comment by ptomato** [comment]
Thanks, I opened https://github.com/tc39/proposal-temporal/issues/2383

Since this doesn't happen with the ISO calendar I assume it's a bug in the non-ISO calendar handling, which is mostly identical to the spec polyfill. We should add tests for this in test262.
