### ISSUE TITLE
Type error: ',' expected when executing yarn build

### ISSUE THREAD

**Issue by abrahamcalsin** [js-temporal/temporal-polyfill#186]
I get the error in production or when I run yarn build, this is the error in the terminal:
![image](https://user-images.githubusercontent.com/77748010/194593178-333355ff-4413-42ab-b0e6-3cab8b716f10.png)

---

And this the error I get in Vercel:
![image](https://user-images.githubusercontent.com/77748010/194595000-13cf29ce-ce69-46f1-ace3-822524f9c789.png)

---

I don't understand why the error occurred, one way to avoid this error was to comment out or delete this line of code `import { type Temporal } from '@js-temporal/polyfill';` in the `node_modules` folder and I don't know if this is a good solution.

Is there any other solution for this error?

**Comment by ptomato** [comment]
I'm not familiar with this error. At first guess, it looks like you might be missing a transpilation step: whatever tool is giving this error, seems not to understand the `import { type ... }` syntax. Maybe it's trying to interpret TypeScript code as JavaScript.

**Comment by abrahamcalsin** [comment]
> Typescripts type imports look like
> 
> `import type {thing} from 'module-name';`
> 
> See examples within our repo:
> 
> https://github.com/js-temporal/temporal-polyfill/blob/6f3c42c90460fa0917e228b5724d7b462c052fd8/lib/intl.ts#L18

Well this solves the error in the local environment, now the question would be, how do I make this solution to be reflected on the server. Since the `node_modules` folder is not pushed to the remote side.

**Comment by gilmoreorless** [comment]
According to the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/2/modules.html#inline-type-imports), the `import { type Temporal }` syntax is valid but was only introduced in TypeScript 4.5. If you're using an older TS version, that would explain the error.

Based on the file path in the error message, this looks to be coming from the `@contentlayer/utils` package. A quick bit of digging reveals this is the source file: https://github.com/contentlayerdev/contentlayer/blob/3e294cd1e85f72883edbda91aa67bcd699fb27ea/packages/@contentlayer/utils/src/index.ts
I suggest raising an issue on that repository describing your problem. They might want to change their code to be compatible with a wider range of TS versions.
