### ISSUE TITLE
Broken test script in the last commit

### ISSUE THREAD

**Issue by rraziel** [js-temporal/temporal-polyfill#19]
Hello,

I believe the [last commit](https://github.com/js-temporal/temporal-polyfill/commit/f67e31228aa79966c2de51f181ebbf3b2d40c0f5#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) broke the test script by forgetting a `time` in the command.

I'll make in quick PR in a minute to revert it, I just didn't want to include it in my other PR in case it might have been done on purpose and for the usual reasons doesn't work on Windows or something 😅.

**Comment by ptomato** [comment]
I don't know if it was intentional, but "doesn't work on Windows" seems a good enough reason to remove it.

**Comment by justingrant** [comment]
It was intentional, but I didn't realize that the `time` command doesn't exist on Windows. Thanks for catching this.

**Comment by rraziel** [comment]
Technically it does exist but it... just displays the time (and ignores any argument) 😅
