### ISSUE TITLE
Can't run it in Node

### ISSUE THREAD

**Issue by manake** [js-temporal/temporal-polyfill#217]
I can't run this.

main.js has this and it loads all modules fine except for this one:
```
import { Temporal } from '@js-temporal/polyfill/dist/index.esm.js';
```

And this is the error:
```
node ./main.js
node:internal/errors:491
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/index.esm.js' is not defined by "exports" in D:\project\node_modules\@js-temporal\polyfill\package.json imported from D:\project\main.js
    at new NodeError (node:internal/errors:400:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at packageResolve (node:internal/modules/esm/resolve:872:14)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.13.0
```

**Comment by manake** [comment]
Ok, it worked with `import { Temporal } from '@js-temporal/polyfill';` but on the other system only `import { Temporal } from '@js-temporal/polyfill/dist/index.esm.js';` works and the first option doesn't.

Why is that?

**Comment by 12wrigja** [comment]
This is because our package's `exports` doesn't expose the files within the bundle directly (which is what that error message you shared is telling you): https://github.com/js-temporal/temporal-polyfill/blob/a0972927ec3bbd75966e977839bc1b6bcc13ca1d/package.json#L10

Out of curiousity: what lead you to trying to import the package via the subpath? Is there a document we need to update?

**Comment by manake** [comment]
Thank you.

That's weird:
1. I tried `import { Temporal } from '@js-temporal/polyfill';` and it didn't work.
2. `import { Temporal } from '@js-temporal/polyfill/dist/index.esm.js';` worked just fine.
3. I switched my laptop and tried to run my main.js and I got an error (above), which was unexpected because on the first laptop I had no error with the same exact code and same Node.js version. I think only npm version is different because on the first laptop I'm using v9 and on the second v8.

So, that's what lead to this: `import { Temporal } from '@js-temporal/polyfill';` didn't work on my first node. I don't know how is that possible.

**Comment by 12wrigja** [comment]
It's possible that the change in Node/NPM version changed whether it enforces the exports rules. That stacktrace points to it being enforced entirely within Node, so maybe you were actually using two different major versions of Node on those machines?

Sounds like there's no docs to update - thanks for clarifying.
