### ISSUE TITLE
assertExists in ecmascript.ts throws if exists

### ISSUE THREAD

**Issue by adambrady-corp** [js-temporal/temporal-polyfill#255]
I'm pretty sure the condition on this DEBUG-only function is inverted (should be arg == null):

https://github.com/js-temporal/temporal-polyfill/blob/96c417ccdb389c38fc0da8fd4fdfcd3dcf7e94d9/lib/ecmascript.ts#L149

**Comment by 12wrigja** [comment]
Yep - that's right. I noticed this a couple weeks back but got side-tracked with release management. Note this doesn't affect our released code (as all the assertions are removed from that bundle).
