### ISSUE TITLE
Cannot read properties of undefined (reading 'getPossibleInstantsFor')

### ISSUE THREAD

**Issue by gimyboya** [js-temporal/temporal-polyfill#268]
I am getting the error `TypeError: Cannot read properties of undefined (reading 'getPossibleInstantsFor')` when attempting the following:

```ts
const dateTimeString = "20201001T090000"; // floating date-time
const dateTime = Temporal.PlainDateTime.from(dateTimeString);

dateTime
        .toLocaleString("us-EN", { // <---error stack points to the toLocaleString function
          hour12: false,
          hour: "2-digit",
          minute: "2-digit",
          second: "2-digit",
        })
        .split(":")
        .join("")
```

With that said the following test shows that it fails when the date type is `Temporal.PlainDate` or `Temporal.Instant` and passes when the date type is `Temporal.ZonedDateTime` or the old `Date` implementation:

```ts
it("iCalendarTimeFormat should return time in HHMMSS format", () => {
    const dateTimeString = "20201001T090000"; // floating date-time
    const dateTimeUTCString = "20201001T090000Z"; // UTC date-time

    const dateTime = Temporal.PlainDateTime.from(dateTimeString);
    const dateTimeUTC = Temporal.Instant.from(dateTimeUTCString);
    const zonedUTCDate = dateTime.toZonedDateTime("UTC");
    const oldDate = new Date(dateTime.toString());

    expect(iCalendarTimeFormat(dateTime)).toBe("090000"); <-- Fails
    expect(iCalendarTimeFormat(dateTimeUTC)).toBe("090000"); <--Fails
    expect(iCalendarTimeFormat(zonedUTCDate)).toBe("090000"); <-- Pass
    expect(iCalendarTimeFormat(oldDate)).toBe("090000"); <-- Pass
  });
  ```
  Where the `iCalendarTimeFormat` is as follows:
  
  ```ts
  export function iCalendarTimeFormat(date: Date | DateTime): string {
  return date
    .toLocaleString("us-EN", {
      hour12: false,
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    })
    .split(":")
    .join("");
}
```
  Any idea what the issue is?

**Comment by gimyboya** [comment]
Now that I think about it. It's very likely. VS Code which is based on electron still use a problematic version of chrome and I am not sure when will electron update that which will then be picked up by VS Code when they upgrade electron.

**Comment by justingrant** [comment]
Is the code running inside a VS Code extension?  I'm wondering why VS Code's version of Chromium inside Electron is relevant.

**Comment by gimyboya** [comment]
@justingrant you are right I somehow assumed that this bug is not present in Node hence i thought that my test relied on VS Code chrome but i just filed an issue in Node as well https://github.com/nodejs/node/issues/50301

**Comment by gimyboya** [comment]
I can confirm that this approach fixes the issue (using Vitest)

```ts
beforeAll(() => {
    const originalValues = new Intl.DateTimeFormat().resolvedOptions();
    vi.spyOn(Intl.DateTimeFormat.prototype, "resolvedOptions").mockReturnValue({
      ...originalValues,
      timeZone: "Asia/Kuala_Lumpur",
    });
  });

  afterAll(() => {
    vi.resetAllMocks();
  });
  ```
  when I mock the returned value I don't et that error anymore
