### ISSUE TITLE
Replacement for formatToParts

### ISSUE THREAD

**Issue by megla-tlanghorst** [js-temporal/temporal-polyfill#278]
With the [changes from 4.4](https://github.com/js-temporal/temporal-polyfill/blob/main/CHANGELOG.md#044), doesn't work anymore on `ZonedDateTime`. We use `Intl.DateTimeFormat.formatToParts()` to extract names of the weekdays, which now doesn't work anymore.

Is there any replacement (planned?) to replace this functionality.

**Comment by 12wrigja** [comment]
There are instructions in the release notes explaining the alternatives to that mechanism, depending on what time zone you want the formatting to be done in:

https://github.com/js-temporal/temporal-polyfill/blob/2238550d8132e4feaddd80284a65612a12d7aa35/CHANGELOG.md?plain=1#L6-L17

The change was originally made to avoid the ambiguity of which timezone to use when formatting the output - the timezone in the Intl.DateTimeFormat ctor, the time zone in the ZonedDateTime, or something else?

Can you elaborate on how creating a DateTimeFormat, converting the ZonedDateTime to an Instant, and formatting that Instant using `formatToParts` doesn't work?

**Comment by ptomato** [comment]
> Is there any replacement (planned?) to replace this functionality.

There is a replacement in the pipeline, https://github.com/tc39/proposal-intl-zoneddatetimeformat, although it is at Stage 1 meaning the form of the replacement is not yet known.

That said, if you _just_ need to extract the weekday names, I think you can still do that from a ZonedDateTime:

```js
> Temporal.Now.zonedDateTimeISO().toLocaleString('en', {weekday: 'long'})
'Tuesday'
```

**Comment by megla-tlanghorst** [comment]
> Can you elaborate on how creating a DateTimeFormat, converting the ZonedDateTime to an Instant, and formatting that Instant using formatToParts doesn't work?

Instants being UTC may flip weekdays, so I don't think that works?

> That said, if you just need to extract the weekday names, I think you can still do that from a ZonedDateTime:
> 
> ```js
> > Temporal.Now.zonedDateTimeISO().toLocaleString('en', {weekday: 'long'})
> 'Tuesday'
> ```

That should work, thanks.

**Comment by ptomato** [comment]
(You could also convert the ZonedDateTime to PlainDateTime, that would definitely not flip the weekday and you wouldn't have to set the time zone separately)
