### ISSUE TITLE
How to parse "19/7/21"

### ISSUE THREAD

**Issue by jpillora** [js-temporal/temporal-polyfill#49]
I had a look through https://tc39.es/proposal-temporal/docs/ and there a preset formats, though how would I parse `"19/7/21"` and use format "dd/mm/yy"?

**Comment by ptomato** [comment]
Hi! Parsing any strings not in ISO 8601 format is not part of the Temporal proposal, so it is not included in this polyfill. There is some discussion about adding it on in a future proposal, https://github.com/js-temporal/proposal-temporal-v2/issues/2.

I'd expect that in the shorter term, once Temporal starts shipping in browsers there will be libraries that appear in the ecosystem that provide Moment- or Luxon-like parsing functionality on top of Temporal.

**Comment by jpillora** [comment]
Hey Philip

Oh that’s a shame - seems parsing non-ISO strings would be a fairly common
use case, and if you need moment/luxon anyway then I think Temporal will
have less impact when it lands. Also I’m not sure they’d use Temporal since
that would require them to have 2 code bases, one for Date and one for
Temporal. Which means for many parsing use cases, Temporal just wouldn’t be
option

Take https://pkg.go.dev/time Go’s time package for example, I’ve been both
a Javascript and Go dev for years and  outside of mocking the clock, I’ve
never needed an external package for anything time related in Go

That said, I like the push for a better date time API in JavaScript and I
appreciate your efforts!

**Comment by ptomato** [comment]
Oh, yeah, I'm not suggesting using Moment or Luxon directly, just that I think these libraries with this parsing functionality will exist in the ecosystem once Temporal starts shipping in JS engines.

**Comment by jpillora** [comment]
Parsing functionality already exists in the ecosystem - I’m hoping to avoid
3rd party solutions

**Comment by ptomato** [comment]
My read on this is that the TC39 committee is understandably wary of repeating the mistakes of `Date.parse()` so it would be difficult to get something built in to JS to do this. I expect the way would be to prove this functionality in a third-party library first. Anyway, if there are future updates on this topic, you'll find them at js-temporal/proposal-temporal-v2#2, see you there!

**Comment by jpillora** [comment]
Thanks Philip, will follow that issue
