### ISSUE TITLE
How to handle typing of mutated `let` variables or function parameters?

### ISSUE THREAD

**Issue by justingrant** [js-temporal/temporal-polyfill#64]
A common pattern in our current polyfill code is to reassign variables and parameters. How should we work around TS's limitation that mutating a variable doesn't change its type from TS's perspective?

For example: ([TS playground](https://www.typescriptlang.org/play?ssl=16&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABFOBlKAnGYDmAKAQwC5FwBrMOAdzAEpEBvAWAChFEDEBeRdLXQrQDcrdhgCmUEBiQERbRAHpFicQA8ADuOjiAJoglSZyAJ5aSfbDlFKVBaCAIAbA5OlIoZ8SXKUarAF9WVhRLAQAWACZaADpsCCcQXXEAZzwAcnD02lZlRAA9fMQAeQAjACttKEQYFMQ4YFMtRHTfajB0mLxIgFYAdgBGHJZclXUNJxgIGCgnE0RkhIJ+HA5XIw8vBbhUjuqqOAwyVRmAC3EMVlBIWARkNEwrSMIfMAp22hIUx9xGG04eGF8ARhDZDO4OPJ2HlCogACpbVpvPwdGp1SjVAgpFIwHBgAilJzie5NYnpb4rTrdADMkWigVYQA))

```ts
function toString(a: unknown) {
  a = String(a);
  return a;
  // expected return type: String
  // actual return type: unknown
}

toString(42).includes('4')
// ^^ Object is of type 'unknown'.(2571)

// explicitly declaring a return type doesn't work either
function toString2(a: unknown): string {
  a = String(a);
  return a;
  // ^^ Type 'unknown' is not assignable to type 'string'.(2322)
}
```

There is apparently a future TS proposal https://github.com/microsoft/TypeScript/issues/45870 which may fix this. I [commented](https://github.com/microsoft/TypeScript/issues/45870#issuecomment-930834908) there to ask if it will help us. 

cc @12wrigja

**Comment by 12wrigja** [comment]
Hmm - yes this is a bit problematic.

One potential solution we could use is something like this:

[playground with type assertion functions](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFOBlKAnGYDmAKAQwC5FwBrMOAdzAEpEBvAWAChFEDEBeRdLXQrQDcrdhgCmUEBiQERbRAHpFicQA8ADuOjiAJoglSZyAJ5aSfbDlFKVBaCAIAbA5OlIoZ8SXKUarAF9WVlBIWAQOAGdI8QwoAElIywE1HzAKajoSAmjYqEjENUQYAsjMK0YbGGBEPABCerqigDJm0y04GqKuHsQAIjL+HD7aemYFdigACwxqRDBxKkQAUQxZjDwAcgAhAn1sDRAodvFN4RsglkvWFGT8ABYAJloAOmwIJxBdcUit+7PWMpEAA9YGIADyACMAFbaY4lRCdE6ITa+TKbF54R4AVgA7ABGWjBFhA9QaJwwCAwKBOEyIb4fAhDDiuIweLz0uA-MCbY5UOAYMiqalTWIhcDQeAeNDlXCPQhpDI0WgkQYVcbsTg8O6CeSa3JxRI6gjnBSGdwcPW2EFggAqHNR6T8POKBUoxxykRgODABEhTnEyDgyM2atwGKxAGZHs9AqwgA).

That being said, this isn't great given that it slightly bloats code-size and runtime as those extra checks have to be included. Internal to Google, we have a system like this that removes these checks in production builds, and we could maybe replicate small parts of it here (using `DEBUG`) .

Alternatively, could we simply avoid this pattern and rewrite to new variables? Are we really saving that much memory by mutation parameter variables?

**Comment by ptomato** [comment]
> Alternatively, could we simply avoid this pattern and rewrite to new variables? Are we really saving that much memory by mutation parameter variables?

Agreed, we can even turn on `no-param-reassign` in eslint and just catch all instances of this at once.

**Comment by 12wrigja** [comment]
We fixed this: [eslintrc.yml](https://github.com/js-temporal/temporal-polyfill/blob/e9c439b9a568ef02f618ad33ba7513d204ff8137/.eslintrc.yml#L98-L102) only has that rule turned off in tests.
