### ISSUE TITLE
Release to npm

### ISSUE THREAD

**Issue by justingrant** [js-temporal/temporal-polyfill#84]
We've landed a lot of PRs since the last npm release, so it's a good time to release again soon. 

I think we should probably release before the JSBI changes are landed.

We should also sync with the latest polyfill-temporal changes before releasing.

**Comment by 12wrigja** [comment]
https://github.com/js-temporal/temporal-polyfill/issues/87 I think this should block releasing.

**Comment by 12wrigja** [comment]
#99 has merged, and we've issued the [v0.3.0](https://github.com/js-temporal/temporal-polyfill/releases/tag/v0.3.0) release!

**Comment by justingrant** [comment]
Whoo-hoo!  Thanks James both for the release and for your overall amazing contributions to Temporal!
