### ISSUE TITLE
Enable `strictNullChecks` and `strictPropertyInitialization` in TS compilation

### ISSUE THREAD

**Issue by justingrant** [js-temporal/temporal-polyfill#98]
`strictNullChecks` and `strictPropertyInitialization` are currently commented out in tsconfig.json. At some point we should fix the 300+ TS errors that show up with these flags enabled.

**Comment by jens-ox** [comment]
Hi Justin! If you want I can look into it. I wanted to start working with the new Temporal APIs, and this seems like a nice starting point. 😊

**Comment by justingrant** [comment]
Fixed in #109
